version: "3.4"

services:
  elasticsearch:
    image: elasticsearch:7.4.1
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200

  kibana:
    image: kibana:7.4.1
    ports:
      - 5601:5601

  python:
    build:
      context: ./
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./:/code
    working_dir: /code
